default_stages: [commit-msg]
fail_fast: false

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        args: ["--config=ci/commitlint.yaml"]
        additional_dependencies: ["conventional-changelog-conventionalcommits"]
